#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'countingValleys' function below.
#
# The function is expected to return an INTEGER.
# The function accepts following parameters:
#  1. INTEGER steps
#  2. STRING path
#

def countingValleys(path,steps):
    #from logging import _Level
    lev=0
    vcount=0
    for i in range(path):
        if steps[i] =="U":
            lev +=1
        elif steps[i] =="D":
            lev -=1
        if lev == 0 and steps[i] =="U":
            vcount +=1
    
    return vcount


if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    steps = int(input().strip())

    path = input()

    result = countingValleys(steps, path)

    fptr.write(str(result) + '\n')

    fptr.close()
