#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'insertionSort1' function below.
#
# The function accepts following parameters:
#  1. INTEGER n
#  2. INTEGER_ARRAY arr
#

def insertionSort1(n, arr):
    x=arr[n-1]
    while True:
        if x < arr [n-2] and n-1>0 :
            arr[n-1]=arr[n-2]
            print(*arr)
            n-=1
        else:
            arr[n-1]=x
            print(*arr)
            break
        

if __name__ == '__main__':
    n = int(input().strip())

    arr = list(map(int, input().rstrip().split()))

    insertionSort1(n, arr)
